### ISSUE TITLE
How do I work this thing

### ISSUE THREAD

**Issue by CoyleJosh** [charlesbos/team_s_scrape#1]
Hey Guys (I'm guessing it's Charles reading this) I have absolutely no idea how to use this program at all. I saw Charles using some commands and stuff to commit changes to the master but have no idea.

HELP PLS.

**Comment by charlesbos** [comment]
Hi there. I did upload a document to our shared drive a little while back which went through the basics. It was called Git & Github.doc

I'm a bit too tired to do any explaining tonight but I'd be more than happy to help  you or anyone else who's having trouble with this tomorrow. 

Charles

**Comment by CoyleJosh** [comment]
Awesome thanks, I'll try using the doc :) just done a couple of additional products for Tesco Sainsburys and Waitrose but every little helps I guess... No pun intended.

**Comment by charlesbos** [comment]
Great stuff. Well as there don't seem to be any further problems I'll close this now.
